# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/CK/Desktop/Vivado/FMCW3/FMCW3.srcs/sources_1/bd/microblaze/ip/microblaze_microblaze_0_5/microblaze_microblaze_0_5.xci
# IP: The module: 'microblaze_microblaze_0_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/CK/Desktop/Vivado/FMCW3/FMCW3.gen/sources_1/bd/microblaze/ip/microblaze_microblaze_0_5/microblaze_microblaze_0_5.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_microblaze_0_5'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/CK/Desktop/Vivado/FMCW3/FMCW3.gen/sources_1/bd/microblaze/ip/microblaze_microblaze_0_5/microblaze_microblaze_0_5_ooc_debug.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_microblaze_0_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/CK/Desktop/Vivado/FMCW3/FMCW3.gen/sources_1/bd/microblaze/ip/microblaze_microblaze_0_5/microblaze_microblaze_0_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_microblaze_0_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/CK/Desktop/Vivado/FMCW3/FMCW3.srcs/sources_1/bd/microblaze/ip/microblaze_microblaze_0_5/microblaze_microblaze_0_5.xci
# IP: The module: 'microblaze_microblaze_0_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/CK/Desktop/Vivado/FMCW3/FMCW3.gen/sources_1/bd/microblaze/ip/microblaze_microblaze_0_5/microblaze_microblaze_0_5.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_microblaze_0_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/CK/Desktop/Vivado/FMCW3/FMCW3.gen/sources_1/bd/microblaze/ip/microblaze_microblaze_0_5/microblaze_microblaze_0_5_ooc_debug.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_microblaze_0_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/CK/Desktop/Vivado/FMCW3/FMCW3.gen/sources_1/bd/microblaze/ip/microblaze_microblaze_0_5/microblaze_microblaze_0_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_microblaze_0_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
