# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ck/Desktop/Workspace/FPGA_Workspace/Vivado/FMCW3_100T/FMCW3.srcs/sources_1/bd/microblaze/ip/microblaze_mdm_1_4/microblaze_mdm_1_4.xci
# IP: The module: 'microblaze_mdm_1_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ck/Desktop/Workspace/FPGA_Workspace/Vivado/FMCW3_100T/FMCW3.gen/sources_1/bd/microblaze/ip/microblaze_mdm_1_4/microblaze_mdm_1_4.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_mdm_1_4'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/ck/Desktop/Workspace/FPGA_Workspace/Vivado/FMCW3_100T/FMCW3.gen/sources_1/bd/microblaze/ip/microblaze_mdm_1_4/microblaze_mdm_1_4_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_mdm_1_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/ck/Desktop/Workspace/FPGA_Workspace/Vivado/FMCW3_100T/FMCW3.gen/sources_1/bd/microblaze/ip/microblaze_mdm_1_4/microblaze_mdm_1_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_mdm_1_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/ck/Desktop/Workspace/FPGA_Workspace/Vivado/FMCW3_100T/FMCW3.srcs/sources_1/bd/microblaze/ip/microblaze_mdm_1_4/microblaze_mdm_1_4.xci
# IP: The module: 'microblaze_mdm_1_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ck/Desktop/Workspace/FPGA_Workspace/Vivado/FMCW3_100T/FMCW3.gen/sources_1/bd/microblaze/ip/microblaze_mdm_1_4/microblaze_mdm_1_4.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_mdm_1_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/ck/Desktop/Workspace/FPGA_Workspace/Vivado/FMCW3_100T/FMCW3.gen/sources_1/bd/microblaze/ip/microblaze_mdm_1_4/microblaze_mdm_1_4_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_mdm_1_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/ck/Desktop/Workspace/FPGA_Workspace/Vivado/FMCW3_100T/FMCW3.gen/sources_1/bd/microblaze/ip/microblaze_mdm_1_4/microblaze_mdm_1_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_mdm_1_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
